project:
  type: website

website:
  title: "Poulami Sarker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.pdf
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true

editor: visual

